### PR TITLE
add terminal-like caret and fake command line

### PR DESCRIPTION
**Pull request by mikeyrayvon**

### CODE REVIEW

**Comment by mixcas** [comment]
I don't understand what this does. I understand the focus parts tho.
Why are we copying text from the input to a span?
What is `#caret`?

**Comment by mixcas** [comment]
Ok,Ii kinda understand what this is for. I think this is not the best solution for showing a carat.

**Comment by mikeyrayvon** [comment]
lol i h8 you

**Comment by mikeyrayvon** [comment]
What is #caret? what is #googlesearch?

**Comment by mixcas** [comment]
I gave it a good thought last night, this is actually fine.
Although, is it supposed to look like this?


I'm gonna merge it. :)

**Comment by varffs** [comment]
No idea why it looks like that for you tho. Cus on mine is looks correct.

**Pull request merged**
